// import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// import ConsultationInvite from "@/components/ConsultationInvite";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//         <ConsultationInvite/>
//       </body>
//     </html>
//   );
// }

import ConsultationInvite from "@/components/ConsultationInvite";
import ContactInfo from "@/components/ContactInfo";
export default function AboutLayout({ children }) {
  return (
    <div className="about-page-wrapper">
      {children}
      <ConsultationInvite/>
      <ContactInfo />
    </div>
  );
}
