// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import TopNav from "@/components/TopNav";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import HeroCoursel from "@/components/HeroCoursel";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <TopNav/>
//         <Navbar/>
//         <HeroCoursel  />
//         {children}
//         <Footer/>
//       </body>
//     </html>
//   );
// }




import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import TopNav from "@/components/TopNav";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import HeroCoursel from "@/components/HeroCoursel";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata = {
  title: {
    default: "Your Company Name",
    template: "%s | Your Company Name",
  },
  description:
    "We deliver excellence in Electrical, Civil, Mechanical and Telecommunication services.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.variable} ${geistMono.variable} font-sans antialiased min-h-screen flex flex-col`}
      >
        <TopNav />
        <Navbar />
        <HeroCoursel />

        <main className="flex-grow">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
